[package]
name = "dndlib"
version = "0.1.0"
edition = "2024"

[lib]
name = "dndlib"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "load_spells"
jest = false
doc = false

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
console_error_panic_hook = "0.1.7"
env_logger = "0.11.10"
lazy_static = "1.5.0"
log = "0.4.32"
regex = "1.12.3"
ron = "0.12.2"
scraper = "0.26.0"
serde = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
thiserror = "2.0.18"
tsify = { git = "https://github.com/madonoharu/tsify"}
unidecode = "0.3.0"
wasm-bindgen = "0.2.125"
